HOSTNAME = 'localhost'
PORT = '3306'
DATABASE = 'forensicsdb'
USERNAME = 'zyr'
PASSWORD = '123456'
SQLALCHEMY_DATABASE_URI = rf'mysql+pymysql://{USERNAME}:{PASSWORD}@{HOSTNAME}:{PORT}/{DATABASE}?charset=utf8mb4'
